doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # only these lines are added additionally
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
#            sluggable:
#                type: annotation
#                alias: Gedmo
#                prefix: Gedmo\Sluggable\Entity
#                # make sure vendor library location is correct
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/src/Sluggable/"
#            timestampable:
#                type: annotation
#                alias: Gedmo
#                prefix: Gedmo\Timestampable\Entity
#                # make sure vendor library location is correct
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/src/Timestampable/"